### ISSUE TITLE
02. Install a Stater project (empty project) in Angular CLI https://cli.angular.io/

### ISSUE THREAD

**Issue by pandima24** [pandima24/parse-workerscompensation.com#4]
installed but ng command not working

**Comment by pandima24** [comment]
solved

**Comment by pandima24** [comment]
The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
    at Object.<anonymous> (C:\Users\Gopal\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Gopal\AppData\Roaming\npm\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by pandima24** [comment]
i think i have to have a different compiler.cli  pkg as per google results.

**Comment by pandima24** [comment]
i reinstalled the entire angular 2 times but seems the problem is obvious and needs an updated pkg

**Comment by gnusiva** [comment]
i reinstalled the entire angular 2 times but seems the problem is obvious and needs an updated pkg

in the above line you ment angular cli ?
if so how did you reinstall angular cli?
you can install angular cli by typing " npm install -g @angular/cli " 
once you installed, close that terminal and open one new terminal and try typing " ng " 
if it is installed properly, you will get some message from ng, other wise you get error message like ng is not internal or external command. 

if you dont get things working, simply delete all @angular/cli directory which resides in "C:\Users\Gopal\AppData\Roaming\npm\node_modules"  and try installing " npm install -g @angular/cli " again.

**Comment by pandima24** [comment]
i did it atleast 5 times it isnt working
iam not sure what did i do wrong

**Comment by pandima24** [comment]
<img width="674" alt="angular installation" src="https://user-images.githubusercontent.com/32661462/32084812-67cc5926-ba99-11e7-8771-dcb0cdde1c24.PNG">

**Comment by pandima24** [comment]
is it done ?
doing it many a items i was confused whether i did it right

**Comment by pandima24** [comment]
if it is correct close the issue

**Comment by pandima24** [comment]
<img width="674" alt="new empty project angular" src="https://user-images.githubusercontent.com/32661462/32085191-9f83a570-ba9b-11e7-8d7d-9fff2ef3e541.PNG">

**Comment by pandima24** [comment]
![image](https://user-images.githubusercontent.com/32661462/32085254-f1463bb6-ba9b-11e7-95ad-5b334de043bb.png)
